cask "font-ume" do
  version "670"
  sha256 "92c4e4f40ddb4285f99240fb28fa19808d586cb3aa3fccb348ee9da940ca3e35"

  url "https://web.archive.org/web/20220212055714if_/https://free.nchc.org.tw/osdn//ume-font/22212/umefont_#{version}.7z"
  name "Ume-font"
  homepage "https://web.archive.org/web/20250214091915/https://ja.osdn.net/projects/ume-font"

  font "umefont_#{version}/ume-hgo4.ttf"
  font "umefont_#{version}/ume-hgo5.ttf"
  font "umefont_#{version}/ume-pgc4.ttf"
  font "umefont_#{version}/ume-pgc5.ttf"
  font "umefont_#{version}/ume-pgo4.ttf"
  font "umefont_#{version}/ume-pgo5.ttf"
  font "umefont_#{version}/ume-pgs4.ttf"
  font "umefont_#{version}/ume-pgs5.ttf"
  font "umefont_#{version}/ume-pmo3.ttf"
  font "umefont_#{version}/ume-pms3.ttf"
  font "umefont_#{version}/ume-tgc4.ttf"
  font "umefont_#{version}/ume-tgc5.ttf"
  font "umefont_#{version}/ume-tgo4.ttf"
  font "umefont_#{version}/ume-tgo5.ttf"
  font "umefont_#{version}/ume-tgs4.ttf"
  font "umefont_#{version}/ume-tgs5.ttf"
  font "umefont_#{version}/ume-tmo3.ttf"
  font "umefont_#{version}/ume-tms3.ttf"
  font "umefont_#{version}/ume-ugo4.ttf"
  font "umefont_#{version}/ume-ugo5.ttf"
end
